extends RefCounted
class_name EquipmentProperties

# Using a collated enum for now since idk how to keep categories but let me
#  add these to gear in editor
enum PROPERTIES {
	ONE_HANDED,
	TWO_HANDED,
	THROWN,
	WEIGHTED,
	SHORT,
	STANDARD,
	LONG,
	FLEXIBLE,
	FIST,
	TENSION,
	GUNPOWDER,
	LOADING,
	SLASHING,
	PIERCING,
	BLUNT,
	CLOTH,
	LIGHT,
	MEDIUM,
	HEAVY,
	SHIELD,
}

# Using arrays to collect enum into groups
const WEAPON_PROPERTIES: Array[PROPERTIES] = [PROPERTIES.ONE_HANDED, PROPERTIES.TWO_HANDED, PROPERTIES.THROWN, PROPERTIES.WEIGHTED]

const MELEE_PROPERTIES: Array[PROPERTIES] = [PROPERTIES.SHORT, PROPERTIES.STANDARD, PROPERTIES.LONG, PROPERTIES.FLEXIBLE, PROPERTIES.FIST]

const RANGED_PROPERTIES: Array[PROPERTIES] = [PROPERTIES.TENSION, PROPERTIES.GUNPOWDER, PROPERTIES.LOADING]

const DAMAGE_TYPES: Array[PROPERTIES] = [PROPERTIES.SLASHING, PROPERTIES.PIERCING, PROPERTIES.BLUNT]

const ARMORS: Array[PROPERTIES] = [PROPERTIES.CLOTH, PROPERTIES.LIGHT, PROPERTIES.MEDIUM, PROPERTIES.HEAVY, PROPERTIES.SHIELD]

enum SLOT {
	HEAD,
	TORSO,
	LEGS,
	ARMS,
	LEFT_ARM,
	RIGHT_ARM,
	OTHER
}